
Resources:
  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: GluePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - glue:*
                Resource: "*"

  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl-nishant
        ScriptLocation: s3://nishant-glue-bucket-234/scripts/job-6.py
      DefaultArguments:
        "--job-language": "python"
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      Name: MyGlueJob
      Role: !GetAtt GlueRole.Arn